from typing import Protocol


class TmuxLinkProtocol(Protocol):
    def ensure_session(self, session_name: str, start_directory: str) -> None: ...

    def attach(self, session_name: str) -> None: ...

    def select_pane(self, pane_id: str) -> None: ...

    def window_id_for_pane(self, pane_id: str) -> str | None: ...

    def session_name_for_pane(self, pane_id: str) -> str | None: ...

    def active_window_id(self, session_name: str) -> str | None: ...

    def mark_window(self, window_id: str) -> None: ...

    def unmark_window(self, window_id: str) -> None: ...

    def last_activity_seconds_ago(self, session_name: str) -> float: ...

    def display_message(self, text: str, session_name: str) -> None: ...
