from typing import Protocol


class TmuxLinkProtocol(Protocol):
    def ensure_session(self) -> None: ...

    def attach(self) -> None: ...

    def select_pane(self, pane_id: str) -> None: ...

    def seconds_since_last_keystroke(self) -> float | None: ...

    def window_id_for_pane(self, pane_id: str) -> str | None: ...

    def active_window_id(self) -> str | None: ...

    def mark_window(self, window_id: str) -> None: ...

    def unmark_window(self, window_id: str) -> None: ...
